name: UI Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # This is set to run at 12:00 AM GMT+8 (4:00 PM UTC)
    - cron: "0 16 * * *"
  workflow_dispatch:
    inputs:
      test_suite:
        description: "Test suite to run"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - logo_and_header
          - buttons
          - dropdown
          - searchbar
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
          
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2
          
      - name: Start ChromeDriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest pytest-html pytest-xdist webdriver_manager
          
      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.test_suite }}" = "all" ] || [ "${{ github.event_name }}" = "schedule" ]; then
            pytest Test/System\ Testing/UI\ Test/*.py -n auto --html=report.html --self-contained-html
          elif [ "${{ github.event.inputs.test_suite }}" = "logo_and_header" ]; then
            pytest Test/System\ Testing/UI\ Test/S1_1_UI-LogoAndHeader.py -n auto --html=report.html --self-contained-html
          elif [ "${{ github.event.inputs.test_suite }}" = "buttons" ]; then
            pytest Test/System\ Testing/UI\ Test/S1_2_UI-Btn_Masjid.py Test/System\ Testing/UI\ Test/S1_3_UI-Btn_Surat.py Test/System\ Testing/UI\ Test/S1_4_UI-Btn_Lain.py -n auto --html=report.html --self-contained-html
          elif [ "${{ github.event.inputs.test_suite }}" = "dropdown" ]; then
            pytest Test/System\ Testing/UI\ Test/S1_5_UI-Dropdown_Negeri.py -n auto --html=report.html --self-contained-html
          elif [ "${{ github.event.inputs.test_suite }}" = "searchbar" ]; then
            pytest Test/System\ Testing/UI\ Test/S1_6_UI-Searchbar.py -n auto --html=report.html --self-contained-html
          fi
        env:
          PYTHONPATH: ${{ github.workspace }}
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html
          
      - name: Upload error screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: error-screenshots
          path: error-screenshots/